sudo: required
services:
  - docker

before_install:
  - docker build -t shashank/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run shashank/react-test npm test -- --coverage

after_success:
  - sudo docker build -t imshashankraj/multi-client ./client
  - sudo docker build -t imshashankraj/multi-nginx ./nginx
  - sudo docker build -t imshashankraj/multi-server ./server
  - sudo docker build -t imshashankraj/multi-worker ./worker
  ## Log into the Docker CLI - Skip Special Chars
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  ## Take those images and push them to docker hub
  - sudo docker push imshashankraj/multi-client
  - sudo docker push imshashankraj/multi-nginx
  - sudo docker push imshashankraj/multi-server
  - sudo docker push imshashankraj/multi-worker

